// Shared Ayah of the Day selection utilities

// Curated list of verses that work well for cards - researched from popular Quran apps
// These verses are meaningful, inspirational, and have concise translations that fit well in cards
export const CARD_FRIENDLY_VERSES: Array<{ surahId: number; verseNumber: number }> = [
  { surahId: 2, verseNumber: 286 },
  { surahId: 3, verseNumber: 159 },
  { surahId: 94, verseNumber: 5 },
  { surahId: 94, verseNumber: 6 },
  { surahId: 13, verseNumber: 28 },
  { surahId: 65, verseNumber: 3 },
  { surahId: 2, verseNumber: 153 },
  { surahId: 39, verseNumber: 53 },
  { surahId: 14, verseNumber: 7 },
  { surahId: 3, verseNumber: 173 },
  { surahId: 28, verseNumber: 77 },
  { surahId: 25, verseNumber: 74 },
  { surahId: 17, verseNumber: 80 },
  { surahId: 2, verseNumber: 201 },
  { surahId: 3, verseNumber: 8 },
  { surahId: 7, verseNumber: 23 },
  { surahId: 25, verseNumber: 65 },
  { surahId: 18, verseNumber: 10 },
  { surahId: 3, verseNumber: 147 },
  { surahId: 59, verseNumber: 10 },
  { surahId: 40, verseNumber: 7 },
  { surahId: 23, verseNumber: 118 },
  { surahId: 17, verseNumber: 24 },
  { surahId: 12, verseNumber: 53 },
  { surahId: 20, verseNumber: 114 },
  { surahId: 1, verseNumber: 1 },
  { surahId: 1, verseNumber: 2 },
  { surahId: 1, verseNumber: 5 },
  { surahId: 112, verseNumber: 1 },
  { surahId: 113, verseNumber: 1 },
  { surahId: 114, verseNumber: 1 },
  { surahId: 55, verseNumber: 13 },
  { surahId: 2, verseNumber: 255 },
  { surahId: 24, verseNumber: 35 },
  { surahId: 57, verseNumber: 4 },
  { surahId: 50, verseNumber: 16 },
  { surahId: 2, verseNumber: 152 },
  { surahId: 29, verseNumber: 45 },
  { surahId: 8, verseNumber: 45 },
  { surahId: 33, verseNumber: 41 },
  { surahId: 76, verseNumber: 25 },
  { surahId: 87, verseNumber: 1 },
  { surahId: 96, verseNumber: 1 },
  { surahId: 103, verseNumber: 1 },
  { surahId: 103, verseNumber: 2 },
  { surahId: 103, verseNumber: 3 },
  { surahId: 108, verseNumber: 1 },
  { surahId: 110, verseNumber: 1 },
  { surahId: 111, verseNumber: 1 },
  { surahId: 109, verseNumber: 1 },
  { surahId: 107, verseNumber: 1 },
  { surahId: 106, verseNumber: 1 },
  { surahId: 105, verseNumber: 1 },
  { surahId: 104, verseNumber: 1 },
  { surahId: 102, verseNumber: 1 },
  { surahId: 101, verseNumber: 1 },
  { surahId: 100, verseNumber: 1 },
  { surahId: 99, verseNumber: 1 },
  { surahId: 98, verseNumber: 1 },
  { surahId: 97, verseNumber: 1 },
  { surahId: 95, verseNumber: 1 },
  { surahId: 93, verseNumber: 1 },
  { surahId: 92, verseNumber: 1 },
  { surahId: 91, verseNumber: 1 },
  { surahId: 90, verseNumber: 1 },
  { surahId: 89, verseNumber: 1 },
  { surahId: 88, verseNumber: 1 },
  { surahId: 86, verseNumber: 1 },
  { surahId: 85, verseNumber: 1 },
  { surahId: 84, verseNumber: 1 },
  { surahId: 83, verseNumber: 1 },
  { surahId: 82, verseNumber: 1 },
  { surahId: 81, verseNumber: 1 },
  { surahId: 80, verseNumber: 1 },
  { surahId: 79, verseNumber: 1 },
  { surahId: 78, verseNumber: 1 },
  { surahId: 4, verseNumber: 86 },
  { surahId: 4, verseNumber: 149 },
  { surahId: 5, verseNumber: 32 },
  { surahId: 6, verseNumber: 160 },
  { surahId: 7, verseNumber: 56 },
  { surahId: 7, verseNumber: 180 },
  { surahId: 8, verseNumber: 2 },
  { surahId: 10, verseNumber: 62 },
  { surahId: 11, verseNumber: 6 },
  { surahId: 12, verseNumber: 87 },
  { surahId: 15, verseNumber: 49 },
  { surahId: 16, verseNumber: 18 },
  { surahId: 16, verseNumber: 97 },
  { surahId: 17, verseNumber: 37 },
  { surahId: 17, verseNumber: 81 },
  { surahId: 20, verseNumber: 25 },
  { surahId: 21, verseNumber: 87 },
  { surahId: 23, verseNumber: 99 },
  { surahId: 24, verseNumber: 2 },
  { surahId: 24, verseNumber: 26 },
  { surahId: 25, verseNumber: 63 },
  { surahId: 26, verseNumber: 80 },
  { surahId: 29, verseNumber: 2 },
  { surahId: 30, verseNumber: 54 },
  { surahId: 31, verseNumber: 18 },
  { surahId: 32, verseNumber: 16 },
  { surahId: 33, verseNumber: 35 },
  { surahId: 35, verseNumber: 3 },
  { surahId: 35, verseNumber: 10 },
  { surahId: 36, verseNumber: 82 },
  { surahId: 39, verseNumber: 9 },
  { surahId: 41, verseNumber: 33 },
  { surahId: 42, verseNumber: 40 },
  { surahId: 42, verseNumber: 43 },
  { surahId: 45, verseNumber: 14 },
  { surahId: 49, verseNumber: 10 },
  { surahId: 49, verseNumber: 12 },
  { surahId: 51, verseNumber: 56 },
  { surahId: 52, verseNumber: 48 },
  { surahId: 67, verseNumber: 2 },
  { surahId: 70, verseNumber: 19 },
  { surahId: 70, verseNumber: 20 },
  { surahId: 70, verseNumber: 21 },
  { surahId: 70, verseNumber: 22 },
  { surahId: 74, verseNumber: 7 },
  { surahId: 77, verseNumber: 1 },
  { surahId: 85, verseNumber: 14 },
  { surahId: 87, verseNumber: 14 },
  { surahId: 90, verseNumber: 4 },
  { surahId: 93, verseNumber: 3 },
  { surahId: 93, verseNumber: 11 },
  { surahId: 102, verseNumber: 8 },
  { surahId: 2, verseNumber: 186 },
  { surahId: 6, verseNumber: 103 },
  { surahId: 2, verseNumber: 195 },
  { surahId: 4, verseNumber: 135 },
  { surahId: 3, verseNumber: 160 },
  { surahId: 5, verseNumber: 90 },
  { surahId: 39, verseNumber: 42 },
  { surahId: 2, verseNumber: 195 },
  { surahId: 2, verseNumber: 277 },
  { surahId: 3, verseNumber: 133 },
  { surahId: 3, verseNumber: 134 },
  { surahId: 3, verseNumber: 139 },
  { surahId: 4, verseNumber: 36 },
  { surahId: 5, verseNumber: 8 },
  { surahId: 6, verseNumber: 99 },
  { surahId: 6, verseNumber: 151 },
  { surahId: 7, verseNumber: 204 },
  { surahId: 10, verseNumber: 109 },
  { surahId: 13, verseNumber: 11 },
  { surahId: 14, verseNumber: 42 },
  { surahId: 15, verseNumber: 85 },
  { surahId: 16, verseNumber: 125 },
  { surahId: 17, verseNumber: 23 },
  { surahId: 18, verseNumber: 49 },
  { surahId: 20, verseNumber: 44 },
  { surahId: 22, verseNumber: 77 },
  { surahId: 23, verseNumber: 1 },
  { surahId: 24, verseNumber: 21 },
  { surahId: 25, verseNumber: 67 },
  { surahId: 29, verseNumber: 64 },
  { surahId: 30, verseNumber: 41 },
  { surahId: 31, verseNumber: 13 },
  { surahId: 33, verseNumber: 70 },
  { surahId: 35, verseNumber: 28 },
  { surahId: 38, verseNumber: 24 },
  { surahId: 40, verseNumber: 60 },
  { surahId: 41, verseNumber: 30 },
  { surahId: 46, verseNumber: 15 },
  { surahId: 49, verseNumber: 6 },
  { surahId: 49, verseNumber: 13 },
  { surahId: 51, verseNumber: 18 },
  { surahId: 58, verseNumber: 7 },
  { surahId: 59, verseNumber: 18 },
  { surahId: 64, verseNumber: 11 },
  { surahId: 67, verseNumber: 3 },
  { surahId: 70, verseNumber: 23 },
  { surahId: 73, verseNumber: 20 },
  { surahId: 75, verseNumber: 3 },
  { surahId: 76, verseNumber: 7 },
  { surahId: 80, verseNumber: 11 },
  { surahId: 93, verseNumber: 5 },
  { surahId: 94, verseNumber: 1 },
  { surahId: 94, verseNumber: 7 },
  { surahId: 94, verseNumber: 8 },
  { surahId: 107, verseNumber: 4 },
  { surahId: 107, verseNumber: 5 },
  { surahId: 2, verseNumber: 45 },
  { surahId: 2, verseNumber: 115 },
  { surahId: 2, verseNumber: 165 },
  { surahId: 2, verseNumber: 208 },
  { surahId: 2, verseNumber: 216 },
  { surahId: 2, verseNumber: 261 },
  { surahId: 3, verseNumber: 92 },
  { surahId: 3, verseNumber: 103 },
  { surahId: 3, verseNumber: 185 },
  { surahId: 4, verseNumber: 17 },
  { surahId: 4, verseNumber: 58 },
  { surahId: 5, verseNumber: 3 },
  { surahId: 5, verseNumber: 27 },
  { surahId: 6, verseNumber: 54 },
  { surahId: 7, verseNumber: 31 },
  { surahId: 9, verseNumber: 129 },
  { surahId: 10, verseNumber: 44 },
  { surahId: 11, verseNumber: 114 },
  { surahId: 12, verseNumber: 64 },
  { surahId: 13, verseNumber: 9 },
  { surahId: 14, verseNumber: 27 },
  { surahId: 17, verseNumber: 9 },
  { surahId: 18, verseNumber: 7 },
  { surahId: 19, verseNumber: 64 },
  { surahId: 20, verseNumber: 82 },
  { surahId: 21, verseNumber: 35 },
  { surahId: 22, verseNumber: 78 },
  { surahId: 23, verseNumber: 2 },
  { surahId: 24, verseNumber: 30 },
  { surahId: 24, verseNumber: 31 },
  { surahId: 25, verseNumber: 7 },
  { surahId: 26, verseNumber: 4 },
  { surahId: 27, verseNumber: 92 },
  { surahId: 28, verseNumber: 54 },
  { surahId: 31, verseNumber: 17 },
  { surahId: 33, verseNumber: 43 },
  { surahId: 34, verseNumber: 39 },
  { surahId: 35, verseNumber: 45 },
  { surahId: 38, verseNumber: 29 },
  { surahId: 39, verseNumber: 10 },
  { surahId: 40, verseNumber: 44 },
  { surahId: 42, verseNumber: 11 },
  { surahId: 43, verseNumber: 85 },
  { surahId: 44, verseNumber: 40 },
  { surahId: 45, verseNumber: 15 },
  { surahId: 47, verseNumber: 7 },
  { surahId: 48, verseNumber: 29 },
  { surahId: 50, verseNumber: 45 },
  { surahId: 53, verseNumber: 32 },
  { surahId: 54, verseNumber: 17 },
  { surahId: 56, verseNumber: 62 },
  { surahId: 57, verseNumber: 20 },
  { surahId: 60, verseNumber: 4 },
  { surahId: 61, verseNumber: 4 },
  { surahId: 62, verseNumber: 9 },
  { surahId: 63, verseNumber: 9 },
  { surahId: 64, verseNumber: 17 },
  { surahId: 65, verseNumber: 2 },
  { surahId: 66, verseNumber: 8 },
  { surahId: 68, verseNumber: 4 },
  { surahId: 69, verseNumber: 1 },
  { surahId: 70, verseNumber: 44 },
  { surahId: 71, verseNumber: 10 },
  { surahId: 72, verseNumber: 18 },
  { surahId: 74, verseNumber: 4 },
  { surahId: 75, verseNumber: 40 },
  { surahId: 76, verseNumber: 24 },
  { surahId: 77, verseNumber: 7 },
  { surahId: 79, verseNumber: 34 },
  { surahId: 80, verseNumber: 24 },
  { surahId: 81, verseNumber: 14 },
  { surahId: 82, verseNumber: 6 },
  { surahId: 83, verseNumber: 17 },
  { surahId: 84, verseNumber: 25 },
  { surahId: 85, verseNumber: 12 },
  { surahId: 86, verseNumber: 10 },
  { surahId: 87, verseNumber: 19 },
  { surahId: 88, verseNumber: 21 },
  { surahId: 89, verseNumber: 27 },
  { surahId: 90, verseNumber: 11 },
  { surahId: 91, verseNumber: 9 },
  { surahId: 92, verseNumber: 5 },
  { surahId: 95, verseNumber: 4 },
  { surahId: 96, verseNumber: 4 },
  { surahId: 97, verseNumber: 5 },
  { surahId: 99, verseNumber: 7 },
  { surahId: 99, verseNumber: 8 },
  { surahId: 100, verseNumber: 6 },
  { surahId: 101, verseNumber: 4 },
  { surahId: 102, verseNumber: 5 },
  { surahId: 103, verseNumber: 3 },
  { surahId: 105, verseNumber: 4 },
  { surahId: 108, verseNumber: 3 },
  { surahId: 109, verseNumber: 6 },
  { surahId: 110, verseNumber: 3 },
  { surahId: 111, verseNumber: 5 },
  { surahId: 112, verseNumber: 4 },
  { surahId: 113, verseNumber: 5 },
  { surahId: 114, verseNumber: 6 },
  { surahId: 53, verseNumber: 55 },
  { surahId: 53, verseNumber: 56 },
  { surahId: 53, verseNumber: 57 },
  { surahId: 53, verseNumber: 58 },
  { surahId: 53, verseNumber: 59 },
  { surahId: 53, verseNumber: 60 },
  { surahId: 53, verseNumber: 61 },
  { surahId: 54, verseNumber: 1 },
  { surahId: 54, verseNumber: 7 },
  { surahId: 54, verseNumber: 22 },
  { surahId: 54, verseNumber: 40 },
  { surahId: 54, verseNumber: 46 },
  { surahId: 54, verseNumber: 53 },
  { surahId: 55, verseNumber: 14 },
  { surahId: 55, verseNumber: 15 },
  { surahId: 55, verseNumber: 17 },
  { surahId: 55, verseNumber: 43 },
  { surahId: 55, verseNumber: 54 },
  { surahId: 55, verseNumber: 56 },
  { surahId: 55, verseNumber: 58 },
  { surahId: 55, verseNumber: 72 },
  { surahId: 55, verseNumber: 76 },
  { surahId: 56, verseNumber: 69 },
  { surahId: 57, verseNumber: 3 },
  { surahId: 57, verseNumber: 12 },
  { surahId: 57, verseNumber: 18 },
  { surahId: 57, verseNumber: 22 },
  { surahId: 57, verseNumber: 28 },
  { surahId: 58, verseNumber: 1 },
  { surahId: 58, verseNumber: 11 },
  { surahId: 58, verseNumber: 22 },
  { surahId: 59, verseNumber: 23 },
  { surahId: 59, verseNumber: 24 },
  { surahId: 60, verseNumber: 8 },
  { surahId: 61, verseNumber: 10 },
  { surahId: 61, verseNumber: 11 },
  { surahId: 61, verseNumber: 12 },
  { surahId: 61, verseNumber: 13 },
  { surahId: 62, verseNumber: 10 },
  { surahId: 63, verseNumber: 10 },
  { surahId: 64, verseNumber: 14 },
  { surahId: 64, verseNumber: 15 },
  { surahId: 65, verseNumber: 4 },
  { surahId: 65, verseNumber: 5 },
  { surahId: 65, verseNumber: 7 },
  { surahId: 66, verseNumber: 6 },
  { surahId: 67, verseNumber: 1 },
  { surahId: 67, verseNumber: 15 },
  { surahId: 68, verseNumber: 51 },
  { surahId: 69, verseNumber: 48 },
  { surahId: 73, verseNumber: 8 },

  { surahId: 59, verseNumber: 22 },  // Names of Allah
  { surahId: 42, verseNumber: 49 },  // To Allah belongs dominion
  { surahId: 67, verseNumber: 14 },  // Does He not know who He created?
  { surahId: 21, verseNumber: 30 },  // Heavens and earth were joined
  { surahId: 36, verseNumber: 40 },  // Sun and moon cosmic order
  { surahId: 41, verseNumber: 53 },  // Signs in horizons
  { surahId: 8, verseNumber: 46 },   // Obey Allah and be patient
  { surahId: 11, verseNumber: 56 },  // I put my trust in Allah
  { surahId: 33, verseNumber: 3 },   // Trust in Allah
  { surahId: 9, verseNumber: 51 },   // Only what Allah has decreed
  { surahId: 2, verseNumber: 155 },  // Test with fear and hunger
  { surahId: 2, verseNumber: 156 },  // Indeed we belong to Allah
  { surahId: 3, verseNumber: 200 },  // Be patient and endure
  { surahId: 90, verseNumber: 17 },  // Encourage patience and mercy
  { surahId: 16, verseNumber: 126 }, // Endure patiently
  { surahId: 14, verseNumber: 34 },  // Blessings countless
  { surahId: 55, verseNumber: 78 },  // Blessed is the name of your Lord
  { surahId: 3, verseNumber: 191 },  // Remember Allah standing
  { surahId: 7, verseNumber: 156 },  // My mercy encompasses all
  { surahId: 4, verseNumber: 110 },  // Whoever seeks forgiveness
  { surahId: 25, verseNumber: 70 },  // Evil deeds replaced with good
  { surahId: 11, verseNumber: 90 },  // Seek forgiveness
  { surahId: 39, verseNumber: 18 },  // Listen and follow the best
  { surahId: 35, verseNumber: 29 },  // Those who recite the Book
  { surahId: 17, verseNumber: 82 },  // Quran is healing
  { surahId: 10, verseNumber: 57 },  // Guidance and healing
  { surahId: 16, verseNumber: 90 },  // Allah commands justice
  { surahId: 42, verseNumber: 15 },  // I believe in what Allah revealed
  { surahId: 18, verseNumber: 46 },  // Wealth and children are adornment
  { surahId: 28, verseNumber: 60 },  // Whatever you have will end
  { surahId: 87, verseNumber: 16 },  // You prefer worldly life
  { surahId: 87, verseNumber: 17 },  // Hereafter is better
  { surahId: 18, verseNumber: 110 }, // I am only a man like you
  { surahId: 49, verseNumber: 11 },  // Do not insult one another
  { surahId: 31, verseNumber: 19 },  // Be moderate in your pace
  { surahId: 17, verseNumber: 53 },  // Say best words
  { surahId: 41, verseNumber: 34 },  // Repel evil with better
  { surahId: 2, verseNumber: 214 },  // When will Allah's help come?
  { surahId: 8, verseNumber: 29 },   // He will grant criterion
  { surahId: 29, verseNumber: 69 },  // Those who strive, We guide
  { surahId: 48, verseNumber: 4 },   // Tranquility into hearts
  { surahId: 2, verseNumber: 257 },  // Allah is Protector
  { surahId: 3, verseNumber: 26 },   // O Allah, Owner of Sovereignty
  { surahId: 3, verseNumber: 27 },   // You cause night to enter day
  { surahId: 6, verseNumber: 59 },   // Keys of the unseen
  { surahId: 27, verseNumber: 62 },  // Who responds to distressed
  { surahId: 55, verseNumber: 26 },  // Everyone will perish
  { surahId: 55, verseNumber: 27 },  // Face of your Lord remains
  { surahId: 89, verseNumber: 28 },  // Return to your Lord
  { surahId: 89, verseNumber: 29 },  // Enter among My servants

];

// Deterministic daily verse selection from curated list
export function getTodayCardVerse(date = new Date()) {
  const startOfYear = new Date(date.getFullYear(), 0, 0);
  const diff = (date.getTime() - startOfYear.getTime()) + ((startOfYear.getTimezoneOffset() - date.getTimezoneOffset()) * 60000);
  const dayOfYear = Math.floor(diff / 86400000); // 1..366
  const index = (dayOfYear - 1) % CARD_FRIENDLY_VERSES.length;
  return CARD_FRIENDLY_VERSES[index];
}
